import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as React from 'react';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import TextField from '@mui/material/TextField';
import Slider from '@mui/material/Slider';
import MenuItem from '@mui/material/MenuItem';
import Stack from '@mui/material/Stack';
import Avatar from '@mui/material/Avatar';
import ColorButtons from '../components/button';
import Grid from '@mui/material/Grid';

const currencies = [
  {
    value: 'USD',
    label: 'Ibuprofen 200mg',
  },
  {
    value: 'EUR',
    label: 'Ibuprofen 400mg',
  },
  {
    value: 'BTC',
    label: 'Ibuprofen 600mg',
  },
  {
    value: 'JPY',
    label: 'Ibuprofen 800mg',
  },
];
const symptoms = ['Pain during sex', 'Bleeding between periods', 'Cramps outside of periods', 'Backache', 'Bloating', 'Frequent urination', 'Painful urination', 'Leg pain', 'Restless leg syndrome', 'Nausea',
'Isomnia', 'Headache', 'Fatigue', 'Abnormal Hair growth', 'Depression & Anxiety']
const Home: NextPage = () => {
  var qfontsize = 20

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Stack direction="row" spacing={2} style = {{ paddingLeft: "100px", paddingBottom: "0px" }}>
        <Avatar
          alt="Remy Sharp"
  
          sx={{ width: 100, height: 100 }}
        />
        <div>
          <Typography variant="h5"  component="div" sx={{ fontWeight: 'bold'}}>
            Remy Sharp
          </Typography>
          <Typography variant="subtitle1" component="div">
            Age: 30
          </Typography>
          <Typography variant="subtitle1" component="div">
            Race: Black
          </Typography>
        </div>
      </Stack>
      {/*<Stack direction="row" spacing={2} style = {{ paddingLeft: "100px"}}>
        <Typography style = {{ backgroundColor: "gray", borderColor: 'black', height: '50px', width: '50px', borderRadius: '50%'}}>
        </Typography>
        <hr style = {{ transform: 'rotate(90deg)', border: "2px solid black",}}/>
        <Typography style = {{ backgroundColor: "gray", borderColor: 'black', height: '50px', width: '50px', borderRadius: '50%'}}>
        </Typography>
  </Stack>*/}
          <CardContent style = {{width: 'fitContent', maxWidth: '70em', height: "100%", border: "1px solid white", paddingLeft: "100px" }}>
            <Typography variant="h6"  component="div" sx={{ fontWeight: 'bold'}}>Questionnaire</Typography>
            <Box style = {{width: 'fitContent', paddingBottom: "10px",  paddingTop: "10px"}}>
            <Typography sx={{ fontSize: qfontsize }} color = 'black' gutterBottom>
              1. How long are your cycles?
            </Typography>
            <Box sx={{
            display: 'flex',
            flexDirection: 'row',
            p: 1,
            m: 1,
          }}>
              <Typography sx={{ fontSize: 15}} style= {{color: 'black', marginRight: '50px'}}className={styles.sub_font_question} gutterBottom>
                How many days  <TextField type="number" style={{
                  width: '60px',
                  height: '5px',
                  borderColor: "black",
              }}
              />
              </Typography>
              <div>
              
              <Typography style={{display: 'inline-block'}}>How many days <br /> between periods?</Typography>
              <TextField type="number" style={{
                  width: '60px',
                  height: '5px',
                  borderColor: "black",
                  display: 'inline-block',
              }}
              />
              </div>
            </Box>
            </Box>
            <Box style = {{width: 'fitContent', paddingBottom: "10px",  paddingTop: "10px"}}>
            <Typography sx={{ fontSize: qfontsize }} color = 'black' gutterBottom>
              2. Approximately what is your pain level during your period?
            </Typography>
            <Box sx={{ width: 'fitContent' }}>
              <Slider
                aria-label="Pain"
                defaultValue={0}
                valueLabelDisplay="auto"
                step={1}
                marks
                min={0}
                max={10}
              />
            </Box>
            </Box>
            <Box style = {{width: 'fitContent', paddingBottom: "10px",  paddingTop: "10px"}}>
            <Typography sx={{ fontSize: qfontsize }} color = 'black' gutterBottom>
              3. What pain management medications do you use and how many a day?
            </Typography>
            <Box sx={{
            display: 'flex',
            flexDirection: 'row',
            p: 1,
            m: 1,
          }}>
              <TextField
            id="outlined-select-currency"
            select
            label="Select"
            helperText="Please select your medication"
          >
            {currencies.map((option) => (
              <MenuItem key={option.value} value={option.value}>
                {option.label}
              </MenuItem>
            ))}
          </TextField>

              <TextField type="number"style={{
                  width: '60px',
                  height: '5px',
                  borderColor: "black",
                  display: 'inline-block',
              }}
              />
            </Box>
            </Box>
            <Box style = {{width: 'fitContent', paddingBottom: "10px",  paddingTop: "10px"}}>
            <Typography sx={{ fontSize: qfontsize }} color = 'black' gutterBottom>
              4. Approximately how many products in a menstrual cycle do you use?
            </Typography>
            <Box sx={{
            display: 'flex',
            flexDirection: 'row',
            p: 1,
            m: 1,
            justifyContent: 'space-between',
          }}>
              <Typography sx={{ fontSize: 15}} style= {{color: 'black', marginRight: '50px'}}className={styles.sub_font_question} gutterBottom>
                Thin  <TextField type="number" style={{
                  width: '60px',
                  height: '5px',
                  borderColor: "black",
              }}
              />
              </Typography>
              <Typography sx={{ fontSize: 15}} style= {{color: 'black', marginRight: '50px'}}className={styles.sub_font_question} gutterBottom>
                Regular  <TextField type="number" style={{
                  width: '60px',
                  height: '5px',
                  borderColor: "black",
              }}
              />
              </Typography>
              <Typography sx={{ fontSize: 15}} style= {{color: 'black', marginRight: '50px'}}className={styles.sub_font_question} gutterBottom>
                Heavy  <TextField type="number" style={{
                  width: '60px',
                  height: '5px',
                  borderColor: "black",
              }}
              />
              </Typography>
              <Typography sx={{ fontSize: 15}} style= {{color: 'black', marginRight: '50px'}}className={styles.sub_font_question} gutterBottom>
                Overnight  <TextField type="number" style={{
                  width: '60px',
                  height: '5px',
                  borderColor: "black",
              }}
              />
              </Typography>
            </Box>
            </Box>
            <Box style = {{width: 'fitContent', paddingBottom: "10px",  paddingTop: "10px"}}>
            <Typography sx={{ fontSize: qfontsize }} color = 'black' gutterBottom>
              5. Do you have the following symptoms?
            </Typography>
            <Grid container spacing={2}>
            {symptoms.map((option, index) => (
                <Grid item key={index} xs={3}>
                    {ColorButtons(option)}
                </Grid>
                ))}
              </Grid>

            </Box>
            
            <Button variant="contained" href="./results" style = {{marginTop: '30px'}}>
            Continue
            </Button>
          </CardContent>
      </main>

    </div>
  )
}

export default Home
